
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: first_name
            description: "The primary key for this table"

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: read_from_bigquery
      description: "Reading data from Bigquery"
      columns:
          - name: id
            description: "PK"
            tests:
                  - unique
                  - not_null

          - name: first_name
            description: "first name of the user"

    - name: users
      description: "Reading data from Bigquery"
      columns:
          - name: id
            description: "PK"
            tests:
                  - unique
                  - not_null

          - name: name
            description: "Name of the user"

          - name: age
            description: "age"

          - name: gender
            description: "gender"

